[network]
name = "stellar-testnet"
rpc_url = "https://soroban-testnet.stellar.org"
passphrase = "Test SDF Network ; September 2015"

[operator]
deployer = "GBTL7SKBHYAROO5CYGTQ4ITTEPTUUPIXDFDYZNDNAYQJ4J5XENX4TGDI"
admin = "GBTL7SKBHYAROO5CYGTQ4ITTEPTUUPIXDFDYZNDNAYQJ4J5XENX4TGDI"
guardian = "GBTL7SKBHYAROO5CYGTQ4ITTEPTUUPIXDFDYZNDNAYQJ4J5XENX4TGDI"

[contracts]
governance = "CBZT5HUXI42TD55GGB5Y7OZZ72IT5SN64ONOGDYS2PFQCOWIT4XOA6MU"
oracle_adapter = "CARSV4BT3II5QONUAOP4D363OUNTTSSZCXSKNNXKZCBJM7Z6UXSNZ3LP"
vault = "CBQ6634Z3UPXFVVHHV2JNSGXHQOZZK62Z65HCAQTINBGXS3IDXKRTRYK"
engine = "CBSUYAO2EYAQVFISJQKG4TNMJPCDCPPFGI25Q3SW2BJPFSKQ45GRGTXN"
order_gateway = "CAJGC2SIV6DFJETJ6ATG5MR6RPNX5HQ26LYA4RGSHF2QPTBS6OJWONL3"
insurance = "CA3VD55APWCYLVN7PYGJ7NPKSQBE3VU4MWVCSKLOYAZI5RFWWR76G2CL"
liquidation = "CDCRNKXTTTOO7IRVC66KZR5QMVGGZIOF2QPJSVELLD7G7F4IVLM2DCMG"
risk = "CAVCW7XCQRA6VYWBKFDABYZGDNUJYHEYKHR4TT6BQBHS6QPDGFJVYBDS"

[assets]
native_xlm = "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC"
circle_usdc = "CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA"
circle_usdc_issuer = "GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5"

[market]
market_id = 1
symbol = "XLM-PERP"
pair = "XLM/USDC"
base_asset = "XLM"
settlement_asset = "USDC"
settlement_asset_contract = "CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA"
initial_oracle_price = "120000000000000000"
initial_oracle_confidence = "1000000000000000"
max_execution_deviation_bps = 100
initial_margin_bps = 1000
maintenance_margin_bps = 500
liquidation_fee_bps = 50
max_leverage_bps = 100000
max_open_interest = "1000000000000000000000000"

[wasm_hashes]
perp_governance = "fe25818fc9430cf001d8573cc49dc86dd7d061791a4a74b3eff82c26c9d85931"
perp_oracle_adapter = "853fd4c9f31e223cf0a6e03f727a4812b71d3f648bf30915ef343e2cc5099e6e"
perp_vault = "06c578a0f08aacfe5a1ee56614acbbb78da2ebd88d39030613f9b926b72e2783"
perp_engine = "f6549f1931345be1bbeda9ba9de1cc1e57827676cdabad0040423e7541a8c785"
perp_order_gateway = "a959b13019f15d2e0ae7b0e1126920e1b895c64e1de8647865ad1963eb42a5a5"
perp_insurance = "b230e85624cfbc46a1532abaa3919a7c6660529032398557e561307e63f48bd1"
perp_liquidation = "6b4d1fcaf812027441e1d0953c79958b82674e828166132c0f832a2d7afbd145"
perp_risk = "c0dc9f73b67588b55aa3aca4735775dc2fbfb29d7a3681f2634b8221522ef251"
